name: CI
on:
  - push
  - pull_request
jobs:
  julia:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.4'
          - '1.5'
        os:
          - ubuntu-latest
        arch:
          - x86
        exclude:
          - os: ubuntu-latest
            arch: x64
            version: 1.4
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        continue-on-error: ${{ matrix.version == 'nightly' || matrix.arch == 'x86' }}
  package:
    name: Aftersuccess
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1'
    - run: |
        julia -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.add("Coverage")
        using Coverage
        Codecov.submit(process_folder())'
       
    - run: |
        julia -e '
        using Pkg;
        Pkg.develop(PackageSpec(path=pwd()));
        Pkg.add("SpikingNeuralNetworks")`
        include("test/test_izhi_model.jl")'
        

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
    - run: |
        julia -e '
        using Pkg;
        Pkg.develop(PackageSpec(path=pwd()));
        Pkg.add("SpikingNeuralNetworks")
        include("test/test_izhi_model.jl")'
        
